### ISSUE TITLE
Order Numbers are getting changed when the order is updated and it breaks the sequence.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-numbers-woocommerce-lite#22]
The client is having an issue when the older orders are getting updated, the order numbers are getting changed and it is breaking the sequence of the order numbers.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/13661

**Comment by upenkapse** [comment]
One more customer has reported this issue. After installing the plugin if we select Order numbers counter as Sequential and update the status of an old order the order number changes and it is assigned a new order number according to the sequential order. The same issue is there in the Pro version too. 

@vishalck @dhruvins one customer who is using the Lite version wants to upgrade to Pro but these issues are stopping him. Another issue he reported is this: https://github.com/TycheSoftwares/custom-order-numbers-for-woocommerce-pro/issues/18

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/18965
